version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: adservice_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ad_service_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: adservice_redis
    ports:
      - "6379:6379"
  
  app:
    build: .
    container_name: adservice_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ad_service_db
    ports:
      - "8080:8080"


  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: adservice_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: adservice_jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318"   # OTLP HTTP
      - "9411:9411"   # Zipkin

volumes:
  db_data:
